name: mdx-net

channels:
  - pytorch
  - nvidia
  - anaconda

dependencies:
  - python=3.8
  - pip
  - cudatoolkit
  - pytorch=1.13.1
  - torchvision=0.14.1
  - ffmpeg==4.3

  - pip:
      - -r requirements.txt
